version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/cqrs/express"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/event-emitter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/grpc"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
