http://localhost:3000/health

###
POST http://localhost:3000/api/commands/tasks
Content-Type: application/json

{
  "title": "Finish CQRS today"
}

###
GET http://localhost:3000/api/queries/tasks/659bf616-96fc-4d4b-8ab2-a53c8bf3dd4d

###
PATCH http://localhost:3000/api/commands/tasks/659bf616-96fc-4d4b-8ab2-a53c8bf3dd4d/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}